services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Tourze\CmsTemplateBundle\Controller\:
    resource: '../../Controller/'
  Tourze\CmsTemplateBundle\Repository\:
    resource: '../../Repository/'
  Tourze\CmsTemplateBundle\Service\:
    resource: '../../Service/'
    public: true
  Tourze\CmsTemplateBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
    public: true
